@startuml

title RELACIONES

PARTNER_POINT "1" *-- "0..*" CLIENT
CLIENT "1" *-- "0..*" REGISTER_TYPE
CLIENT "1" *-- "0..*" USER_LEVEL
BOOKING "1" *-- "0..*" BOOKING_STATE
BOOKING "1" *-- "0..*" PAYMENT_METHOD
BOOKING "1" *-- "0..*" ROOM
BOOKING_DETAIL "1" *-- "0..*" CLIENT
BOOKING_DETAIL "1" *-- "0..*" BOOKING
BOOKING_DETAIL "1" *-- "0..*" PAYMENT_STATE
ROOM_DETAIL "1" *-- "0..*" ROOM
REFUSE "1" *-- "0..*" PAYMENT_STATE
REFUSE "1" *-- "0..*" REFUSE_REASON


SOLICITUDE "1" *-- "0..*" ADMIN
SOLICITUDE "1" *-- "0..*" CLIENT


@enduml
