INSERT INTO public.country (countryid,countrydesc,iso,nicename,iso3,numcode,phonecode,symbol,courtesy,icon) VALUES
	 (3,'ALEMANIA','DE','Germany','DEU',276,49,'+','ALEMANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/de.svg'),
	 (4,'ANDORRA','AD','Andorra','AND',20,376,'+','ANDORREÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ad.svg'),
	 (5,'ANGOLA','AO','Angola','AGO',24,244,'+','ANGOLEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ao.svg'),
	 (35,'BURUNDI','BI','Burundi','BDI',108,257,'+','BURUNDESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bi.svg'),
	 (36,'CAMBOYA','KH','Cambodia','KHM',116,855,'+','CAMBOYANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kh.svg'),
	 (55,'DJIBOUTI','DJ','Djibouti','DJI',262,253,'+','YIBUTIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/dj.svg'),
	 (56,'DOMINICA','DM','Dominica','DMA',212,1767,'+','DOMINIQUESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/dm.svg'),
	 (57,'ECUADOR','EC','Ecuador','ECU',218,593,'+','ECUATORIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ec.svg'),
	 (58,'EGIPTO','EG','Egypt','EGY',818,20,'+','EGIPCIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/eg.svg'),
	 (59,'EL SALVADOR','SV','El Salvador','SLV',222,503,'+','SALVADOREÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sv.svg'),
	 (60,'EMIRATOS ARABES UNIDOS','AE','United Arab Emirates','ARE',784,971,'+','EMIRATÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ae.svg'),
	 (61,'ERITREA','ER','Eritrea','ERI',232,291,'+','ERITREA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/er.svg'),
	 (62,'ESLOVAQUIA','SK','Slovakia','SVK',703,421,'+','ESLOVACA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sk.svg'),
	 (63,'ESLOVENIA','SI','Slovenia','SVN',705,386,'+','ESLOVENA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/si.svg'),
	 (64,'ESPAÑA','ES','Spain','ESP',724,34,'+','ESPAÑOLA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/es.svg'),
	 (65,'ESTADOS UNIDOS','US','United States','USA',840,1,'+','ESTADOUNIDENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/us.svg'),
	 (66,'ESTONIA','EE','Estonia','EST',233,372,'+','ESTONIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ee.svg'),
	 (67,'ETIOPIA','ET','Ethiopia','ETH',231,251,'+','ETIOPE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/et.svg'),
	 (68,'FIJI','FJ','Fiji','FJI',242,679,'+','FIYIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/fj.svg'),
	 (69,'FILIPINAS','PH','Philippines','PHL',608,63,'+','FILIPINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ph.svg'),
	 (70,'FINLANDIA','FI','Finland','FIN',246,358,'+','FINLANDESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/fi.svg'),
	 (71,'FRANCIA','FR','France','FRA',250,33,'+','FRANCESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/fr.svg'),
	 (72,'GABON','GA','Gabon','GAB',266,241,'+','GABONÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ga.svg'),
	 (73,'GAMBIA','GM','Gambia','GMB',270,220,'+','GAMBIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gm.svg'),
	 (74,'GEORGIA','GE','Georgia','GEO',268,995,'+','GEORGIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ge.svg'),
	 (75,'GHANA','GH','Ghana','GHA',288,233,'+','GHANÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gh.svg'),
	 (76,'GIBRALTAR','GI','Gibraltar','GIB',292,350,'+','GIBRALTAREÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gi.svg'),
	 (77,'GRANADA','GD','Grenada','GRD',308,1473,'+','GRENADENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gd.svg'),
	 (78,'GRECIA','GR','Greece','GRC',300,30,'+','GRIEGA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gr.svg'),
	 (79,'GROENLANDIA','GL','Greenland','GRL',304,299,'+','GROENLANDÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gl.svg'),
	 (80,'GUADALUPE','GP','Guadeloupe','GLP',312,590,'+','GUADELUPEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gp.svg'),
	 (81,'GUAM','GU','Guam','GUM',316,1671,'+','GUAMEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gu.svg'),
	 (82,'GUATEMALA','GT','Guatemala','GTM',320,502,'+','GUATEMALTECA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gt.svg'),
	 (83,'GUAYANA FRANCESA','GF','French Guiana','GUF',254,594,'+','GUYANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gf.svg'),
	 (84,'GUERNESEY','GG','Guernsey','GGY',831,44,'+','GUERNESEY','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gg.svg'),
	 (85,'GUINEA','GN','Guinea','GIN',324,224,'+','GUINEANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gn.svg'),
	 (86,'GUINEA ECUATORIAL','GQ','Equatorial Guinea','GNQ',226,240,'+','GUINEANA ECUATORIAL','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gq.svg'),
	 (87,'GUINEA-BISSAU','GW','Guinea-Bissau','GNB',624,245,'+','GUINEANA BISÁUENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gw.svg'),
	 (88,'GUYANA','GY','Guyana','GUY',328,592,'+','GUYANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gy.svg'),
	 (89,'HAITI','HT','Haiti','HTI',332,509,'+','HAITIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ht.svg'),
	 (90,'HONDURAS','HN','Honduras','HND',340,504,'+','HONDUREÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/hn.svg'),
	 (91,'HONG KONG','HK','Hong Kong','HKG',344,852,'+','HONGKONGUÉS','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/hk.svg'),
	 (92,'HUNGRIA','HU','Hungary','HUN',348,36,'+','HÚNGARA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/hu.svg'),
	 (93,'INDIA','IN','India','IND',356,91,'+','INDIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/in.svg'),
	 (94,'INDONESIA','ID','Indonesia','IDN',360,62,'+','INDONESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/id.svg'),
	 (95,'IRAK','IQ','Iraq','IRQ',368,964,'+','IRAQUÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/iq.svg'),
	 (96,'IRAN','IR','Iran, Islamic Republic of','IRN',364,98,'+','IRANÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ir.svg'),
	 (97,'IRLANDA','IE','Ireland','IRL',372,353,'+','IRLANDÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ie.svg'),
	 (98,'ISLA BOUVET','BV','Bouvet Island','BVT',74,47,'+','BOUVETIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bv.svg'),
	 (99,'ISLA DE MAN','IM','Isle of Man','IMN',833,44,'+','MANÉS','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/im.svg'),
	 (100,'ISLA DE NAVIDAD','CX','Christmas Island','CXR',162,61,'+','NAVIDEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cx.svg'),
	 (101,'ISLA NORFOLK','NF','Norfolk Island','NFK',574,672,'+','NORFOLKENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/nf.svg'),
	 (102,'ISLANDIA','IS','Iceland','ISL',352,354,'+','ISLANDESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/is.svg'),
	 (103,'ISLAS CAIMÁN','KY','Cayman Islands','CYM',136,1345,'+','CAIMANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ky.svg'),
	 (231,'TURKMENISTAN','TM','Turkmenistan','TKM',795,993,'+','TURCOMANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tm.svg'),
	 (104,'ISLAS COCOS (KEELING)','CC','Cocos (Keeling) Islands','CCK',166,61,'+','COQUENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cc.svg'),
	 (105,'ISLAS COOK','CK','Cook Islands','COK',184,682,'+','COOKIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ck.svg'),
	 (106,'ISLAS FEROE','FO','Faroe Islands','FRO',234,298,'+','FEROSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/fo.svg'),
	 (107,'ISLAS HEARD Y MCDONALD','HM','Heard Island and McDonald Islands','HMD',334,334,'+','HEARDENSE Y MCDONALDENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/hm.svg'),
	 (108,'ISLAS MALVINAS','FK','Falkland Islands (Malvinas)','FLK',238,500,'+','MALVINENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/fk.svg'),
	 (109,'ISLAS MARIANAS DEL NORTE','MP','Northern Mariana Islands','MNP',580,1670,'+','NORMARIANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mp.svg'),
	 (110,'ISLAS MARSHALL','MH','Marshall Islands','MHL',584,692,'+','MARSHALESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mh.svg'),
	 (111,'ISLAS PITCAIRN','PN','Pitcairn','PCN',612,870,'+','PITCAIRNESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pn.svg'),
	 (112,'ISLAS SALOMÓN','SB','Solomon Islands','SLB',90,677,'+','SOLOMONENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sb.svg'),
	 (113,'ISLAS TURCAS Y CAICOS','TC','Turks and Caicos Islands','TCA',796,1649,'+','TURCOCAIQUEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tc.svg'),
	 (114,'ISLAS VÍRGENES BRITÁNICAS','VG','Virgin Islands, British','VGB',92,1284,'+','VIRGENENSE BRITÁNICA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/vg.svg'),
	 (115,'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS','VI','Virgin Islands, U.S.','VIR',850,1340,'+','VIRGENENSE ESTADOUNIDENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/vi.svg'),
	 (116,'ISRAEL','IL','Israel','ISR',376,972,'+','ISRAELÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/il.svg'),
	 (117,'ITALIA','IT','Italy','ITA',380,39,'+','ITALIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/it.svg'),
	 (118,'JAMAICA','JM','Jamaica','JAM',388,1876,'+','JAMAIQUINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/jm.svg'),
	 (119,'JAPON','JP','Japan','JPN',392,81,'+','JAPONESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/jp.svg'),
	 (120,'JERSEY','JE','Jersey','JEY',832,44,'+','JERSEY','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/je.svg'),
	 (121,'JORDANIA','JO','Jordan','JOR',400,962,'+','JORDANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/jo.svg'),
	 (122,'KAZAJSTAN','KZ','Kazakhstan','KAZ',398,7,'+','KAZAJA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kz.svg'),
	 (123,'KENIA','KE','Kenya','KEN',404,254,'+','KENIATA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ke.svg'),
	 (124,'KIRGUISTAN','KG','Kyrgyzstan','KGZ',417,996,'+','KIRGUISA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kg.svg'),
	 (125,'KIRIBATI','KI','Kiribati','KIR',296,686,'+','KIRIBATIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ki.svg'),
	 (126,'KUWAIT','KW','Kuwait','KWT',414,965,'+','KUWAITÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kw.svg'),
	 (127,'LAOS','LA','Lao Peoples Democratic Republic','LAO',418,856,'+','LAOSIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/la.svg'),
	 (128,'LESOTO','LS','Lesotho','LSO',426,266,'+','LESOTENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ls.svg'),
	 (21,'BARBADOS','BB','Barbados','BRB',52,1246,'+','BARBADENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bb.svg'),
	 (22,'BELGICA','BE','Belgium','BEL',56,32,'+','BELGA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/be.svg'),
	 (23,'BELICE','BZ','Belize','BLZ',84,501,'+','BELICEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bz.svg'),
	 (24,'BENIN','BJ','Benin','BEN',204,229,'+','BENINESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bj.svg'),
	 (25,'BERMUDA','BM','Bermuda','BMU',60,1441,'+','BERMUDEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bm.svg'),
	 (26,'BHUTAN','BT','Bhutan','BTN',64,975,'+','BUTANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bt.svg'),
	 (27,'BIELORUSIA','BY','Belarus','BLR',112,375,'+','BIELORRUSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/by.svg'),
	 (28,'BOLIVIA','BO','Bolivia','BOL',68,591,'+','BOLIVIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bo.svg'),
	 (29,'BOSNIA Y HERZEGOVINA','BA','Bosnia and Herzegovina','BIH',70,387,'+','BOSNIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ba.svg'),
	 (30,'BOTSWANA','BW','Botswana','BWA',72,267,'+','BOTSUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bw.svg'),
	 (31,'BRASIL','BR','Brazil','BRA',76,55,'+','BRASILERA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/br.svg'),
	 (32,'BRUNEI DARUSSALAM','BN','Brunei Darussalam','BRN',96,673,'+','BRUNEANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bn.svg'),
	 (33,'BULGARIA','BG','Bulgaria','BGR',100,359,'+','BÚLGARA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bg.svg'),
	 (34,'BURKINA FASO','BF','Burkina Faso','BFA',854,226,'+','BURKINESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bf.svg'),
	 (129,'LETONIA','LV','Latvia','LVA',428,371,'+','LETÓN','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lv.svg'),
	 (130,'LIBANO','LB','Lebanon','LBN',422,961,'+','LIBANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lb.svg'),
	 (131,'LIBERIA','LR','Liberia','LBR',430,231,'+','LIBERIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lr.svg'),
	 (132,'LIBIA','LY','Libya','LBY',434,218,'+','LIBIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ly.svg'),
	 (6,'ANGUILLA','AI','Anguilla','AIA',660,1264,'+','ANGUILEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ai.svg'),
	 (7,'ANTARTIDA','AQ','Antarctica','',0,0,'+','ANTÁRTICA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/aq.svg'),
	 (8,'ANTIGUA Y BARBUDA','AG','Antigua and Barbuda','ATG',28,1268,'+','ANTIGUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ag.svg'),
	 (9,'ANTILLAS HOLANDESAS','AN','Netherlands Antilles','ANT',530,599,'+','ANTILLANA NEERLANDESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/an.svg'),
	 (10,'ARABIA SAUDI','SA','Saudi Arabia','SAU',682,966,'+','SAUDÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sa.svg'),
	 (11,'ARGELIA','DZ','Algeria','DZA',12,213,'+','ARGELINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/dz.svg'),
	 (12,'ARGENTINA','AR','Argentina','ARG',32,54,'+','ARGENTINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ar.svg'),
	 (13,'ARMENIA','AM','Armenia','ARM',51,374,'+','ARMENIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/am.svg'),
	 (14,'ARUBA','AW','Aruba','ABW',533,297,'+','ARUBEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/aw.svg'),
	 (15,'AUSTRALIA','AU','Australia','AUS',36,61,'+','AUSTRALIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/au.svg'),
	 (16,'AUSTRIA','AT','Austria','AUT',40,43,'+','AUSTRIACA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/at.svg'),
	 (17,'AZERBAIYAN','AZ','Azerbaijan','AZE',31,994,'+','AZERBAIYANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/az.svg'),
	 (18,'BAHAMAS','BS','Bahamas','BHS',44,1242,'+','BAHAMEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bs.svg'),
	 (19,'BAHREIN','BH','Bahrain','BHR',48,973,'+','BAREINÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bh.svg'),
	 (20,'BANGLADESH','BD','Bangladesh','BGD',50,880,'+','BANGLADESÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bd.svg'),
	 (133,'LIECHTENSTEIN','LI','Liechtenstein','LIE',438,423,'+','LIECHTENSTEINENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/li.svg'),
	 (134,'LITUANIA','LT','Lithuania','LTU',440,370,'+','LITUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lt.svg'),
	 (153,'MONGOLIA','MN','Mongolia','MNG',496,976,'+','MONGOLA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mn.svg'),
	 (154,'MONTENEGRO','ME','Montenegro','MNE',499,382,'+','MONTENEGRINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/me.svg'),
	 (155,'MONTSERRAT','MS','Montserrat','MSR',500,1664,'+','MONTSERRATENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ms.svg'),
	 (156,'MOZAMBIQUE','MZ','Mozambique','MOZ',508,258,'+','MOZAMBIQUEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mz.svg'),
	 (157,'MYANMAR','MM','Myanmar','MMR',104,95,'+','BIRMANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mm.svg'),
	 (158,'NAMIBIA','NA','Namibia','NAM',516,264,'+','NAMIBIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/na.svg'),
	 (159,'NAURU','NR','Nauru','NRU',520,674,'+','NAURUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/nr.svg'),
	 (160,'NEPAL','NP','Nepal','NPL',524,977,'+','NEPALESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/np.svg'),
	 (161,'NICARAGUA','NI','Nicaragua','NIC',558,505,'+','NICARAGÜENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ni.svg'),
	 (162,'NIGER','NE','Niger','NER',562,227,'+','NIGERINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ne.svg'),
	 (163,'NIGERIA','NG','Nigeria','NGA',566,234,'+','NIGERIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ng.svg'),
	 (164,'NIUE','NU','Niue','NIU',570,683,'+','NIUEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/nu.svg'),
	 (165,'NORUEGA','NO','Norway','NOR',578,47,'+','NORUEGA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/no.svg'),
	 (166,'NUEVA CALEDONIA','NC','New Caledonia','NCL',540,687,'+','NEOCALDEONIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/nc.svg'),
	 (218,'SVALBARD Y JAN MAYEN','SJ','Svalbard and Jan Mayen','SJM',744,47,'+','SVALBARDESIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sj.svg'),
	 (167,'NUEVA ZELANDIA','NZ','New Zealand','NZL',554,64,'+','NEOZELANDESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/nz.svg'),
	 (168,'OMAN','OM','Oman','OMN',512,968,'+','OMANÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/om.svg'),
	 (169,'PAISES BAJOS','NL','Netherlands','NLD',528,31,'+','NEERLANDESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/nl.svg'),
	 (170,'PAKISTAN','PK','Pakistan','PAK',586,92,'+','PAKISTANÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pk.svg'),
	 (171,'PALAU','PW','Palau','PLW',585,680,'+','PALAUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pw.svg'),
	 (172,'PALESTINA','PS','Palestine, State of','PSE',275,970,'+','PALESTINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ps.svg'),
	 (173,'PANAMA','PA','Panama','PAN',591,507,'+','PANAMEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pa.svg'),
	 (174,'PAPUA NUEVA GUINEA','PG','Papua New Guinea','PNG',598,675,'+','PAPÚ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pg.svg'),
	 (175,'PARAGUAY','PY','Paraguay','PRY',600,595,'+','PARAGUAYA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/py.svg'),
	 (176,'PERU','PE','Peru','PER',604,51,'+','PERUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pe.svg'),
	 (177,'POLINESIA FRANCESA','PF','French Polynesia','PYF',258,689,'+','POLINESIA FRANCÉS','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pf.svg'),
	 (178,'POLONIA','PL','Poland','POL',616,48,'+','POLACA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pl.svg'),
	 (179,'PORTUGAL','PT','Portugal','PRT',620,351,'+','PORTUGUESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pt.svg'),
	 (180,'PUERTO RICO','PR','Puerto Rico','PRI',630,1787,'+','PUERTORRIQUEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pr.svg'),
	 (181,'QATAR','QA','Qatar','QAT',634,974,'+','CATARÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/qa.svg'),
	 (182,'REINO UNIDO','GB','United Kingdom','GBR',826,44,'+','BRITÁNICA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/gb.svg'),
	 (183,'REPUBLICA CENTROAFRICANA','CF','Central African Republic','CAF',140,236,'+','CENTROAFRICANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cf.svg'),
	 (184,'REPUBLICA CHECA','CZ','Czech Republic','CZE',203,420,'+','CHECA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cz.svg'),
	 (185,'REPUBLICA DEMOCRATICA DEL CONGO','CD','Congo, the Democratic Republic of the','COD',180,243,'+','CONGOLEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cd.svg'),
	 (186,'REPUBLICA DOMINICANA','DO','Dominican Republic','DOM',214,1809,'+','DOMINICANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/do.svg'),
	 (187,'REUNION','RE','Reunion','REU',638,262,'+','REUNIONESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/re.svg'),
	 (188,'RUANDA','RW','Rwanda','RWA',646,250,'+','RUANDÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/rw.svg'),
	 (189,'RUMANIA','RO','Romania','ROU',642,40,'+','RUMANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ro.svg'),
	 (190,'RUSIA','RU','Russian Federation','RUS',643,7,'+','RUSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ru.svg'),
	 (191,'SAHARA OCCIDENTAL','EH','Western Sahara','ESH',732,212,'+','SAHARAUI','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/eh.svg'),
	 (192,'SAMOA','WS','Samoa','WSM',882,685,'+','SAMOANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ws.svg'),
	 (193,'SAMOA AMERICANA','AS','American Samoa','ASM',16,1684,'+','SAMOANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/as.svg'),
	 (194,'SAN BARTOLOMÉ','BL','Saint Barthélemy','BLM',652,590,'+','BARTELEMITA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/bl.svg'),
	 (195,'SAN CRISTOBAL Y NEVIS','KN','Saint Kitts and Nevis','KNA',659,1869,'+','SANCRISTOBALEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kn.svg'),
	 (196,'SAN MARINO','SM','San Marino','SMR',674,378,'+','SANMARINENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sm.svg'),
	 (197,'SAN MARTÍN (PARTE FRANCESA)','MF','Saint Martin (French part)','MAF',663,590,'+','SANMARTINENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mf.svg'),
	 (198,'SAN PEDRO Y MIQUELON','PM','Saint Pierre and Miquelon','SPM',666,508,'+','SAINTPIERREÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/pm.svg'),
	 (199,'SAN VICENTE Y LAS GRANADINAS','VC','Saint Vincent and the Grenadines','VCT',670,1784,'+','SANVICENTINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/vc.svg'),
	 (200,'SANTA ELENA, ASCENSION Y TRISTAN DE ACUÑA','SH','Saint Helena, Ascension and Tristan da Cunha','SHN',654,290,'+','SANTAHÉLENA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sh.svg'),
	 (201,'SANTA LUCÍA','LC','Saint Lucia','LCA',662,1758,'+','SANTALUCENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lc.svg'),
	 (202,'SANTO TOMÉ Y PRÍNCIPE','ST','Sao Tome and Principe','STP',678,239,'+','SANTOTOMENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/st.svg'),
	 (203,'SENEGAL','SN','Senegal','SEN',686,221,'+','SENEGALÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sn.svg'),
	 (204,'SERBIA','RS','Serbia','SRB',688,381,'+','SERBIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/rs.svg'),
	 (205,'SEYCHELLES','SC','Seychelles','SYC',690,248,'+','SEYCHELLENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sc.svg'),
	 (206,'SIERRA LEONA','SL','Sierra Leone','SLE',694,232,'+','SIERRALEONÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sl.svg'),
	 (207,'SINGAPUR','SG','Singapore','SGP',702,65,'+','SINGAPURENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sg.svg'),
	 (208,'SIRIA','SY','Syrian Arab Republic','SYR',760,963,'+','SIRIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sy.svg'),
	 (222,'TAYIKISTAN','TJ','Tajikistan','TJK',762,992,'+','TAYIKA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tj.svg'),
	 (223,'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO','IO','British Indian Ocean Territory','IOT',86,246,'+','BRITÁNICO','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/io.svg'),
	 (224,'TERRITORIOS AUSTRALES FRANCESES','TF','French Southern Territories','ATF',260,260,'+','FRANCOS','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tf.svg'),
	 (225,'TIMOR-LESTE','TL','Timor-Leste','TLS',626,670,'+','TIMORÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tl.svg'),
	 (226,'TOGO','TG','Togo','TGO',768,228,'+','TOGOLESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tg.svg'),
	 (227,'TOKELAU','TK','Tokelau','TKL',772,690,'+','TOKELAUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tk.svg'),
	 (228,'TONGA','TO','Tonga','TON',776,676,'+','TONGANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/to.svg'),
	 (229,'TRINIDAD Y TOBAGO','TT','Trinidad and Tobago','TTO',780,1868,'+','TRINITENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tt.svg'),
	 (230,'TUNEZ','TN','Tunisia','TUN',788,216,'+','TUNECINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tn.svg'),
	 (232,'TURQUÍA','TR','Turkey','TUR',792,90,'+','TURCA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tr.svg'),
	 (233,'TUVALU','TV','Tuvalu','TUV',798,688,'+','TUVALUANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tv.svg'),
	 (234,'UCRANIA','UA','Ukraine','UKR',804,380,'+','UCRANIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ua.svg'),
	 (235,'UGANDA','UG','Uganda','UGA',800,256,'+','UGANDÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ug.svg'),
	 (236,'URUGUAY','UY','Uruguay','URY',858,598,'+','URUGUAYA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/uy.svg'),
	 (237,'UZBEKISTAN','UZ','Uzbekistan','UZB',860,998,'+','UZBEKA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/uz.svg'),
	 (238,'VANUATU','VU','Vanuatu','VUT',548,678,'+','VANUATUENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/vu.svg'),
	 (239,'VATICANO','VA','Holy See (Vatican City State)','VAT',336,39,'+','VATICANO','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/va.svg'),
	 (240,'VENEZUELA','VE','Venezuela, Bolivarian Republic of','VEN',862,58,'+','VENEZOLANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ve.svg'),
	 (241,'VIETNAM','VN','Viet Nam','VNM',704,84,'+','VIETNAMITA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/vn.svg'),
	 (242,'WALLIS Y FUTUNA','WF','Wallis and Futuna','WLF',876,681,'+','WALLISIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/wf.svg'),
	 (243,'YEMEN','YE','Yemen','YEM',887,967,'+','YEMENÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ye.svg'),
	 (244,'YIBUTI','DJ','Djibouti','DJI',262,253,'+','YIBUTIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/dj.svg'),
	 (245,'ZAMBIA','ZM','Zambia','ZMB',894,260,'+','ZAMBIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/zm.svg'),
	 (246,'ZIMBABUE','ZW','Zimbabwe','ZWE',716,263,'+','ZIMBABUENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/zw.svg'),
	 (1,'AFGHANISTAN','AF','Afghanistan','AFG',4,93,'+','AFGANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/af.svg'),
	 (2,'ALBANIA','AL','Albania','ALB',8,355,'+','ALBANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/al.svg'),
	 (135,'LUXEMBURGO','LU','Luxembourg','LUX',442,352,'+','LUXEMBURGUÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lu.svg'),
	 (136,'MACAO','MO','Macao','MAC',446,853,'+','MACAENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mo.svg'),
	 (137,'MACEDONIA','MK','Macedonia, the former Yugoslav Republic of','MKD',807,389,'+','MACEDONIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mk.svg'),
	 (138,'MADAGASCAR','MG','Madagascar','MDG',450,261,'+','MALGACHE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mg.svg'),
	 (139,'MALASIA','MY','Malaysia','MYS',458,60,'+','MALASIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/my.svg'),
	 (140,'MALAWI','MW','Malawi','MWI',454,265,'+','MALAUÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mw.svg'),
	 (141,'MALDIVAS','MV','Maldives','MDV',462,960,'+','MALDIVA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mv.svg'),
	 (142,'MALI','ML','Mali','MLI',466,223,'+','MALÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ml.svg'),
	 (143,'MALTA','MT','Malta','MLT',470,356,'+','MALTESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mt.svg'),
	 (144,'MARRUECOS','MA','Morocco','MAR',504,212,'+','MARROQUÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ma.svg'),
	 (145,'MARTINICA','MQ','Martinique','MTQ',474,596,'+','MARTINIQUESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mq.svg'),
	 (146,'MAURICIO','MU','Mauritius','MUS',480,230,'+','MAURICIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mu.svg'),
	 (147,'MAURITANIA','MR','Mauritania','MRT',478,222,'+','MAURITANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mr.svg'),
	 (148,'MAYOTTE','YT','Mayotte','MYT',175,269,'+','MAYOTTEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/yt.svg'),
	 (149,'MEXICO','MX','Mexico','MEX',484,52,'+','MEXICANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mx.svg'),
	 (150,'MICRONESIA','FM','Micronesia, Federated States of','FSM',583,691,'+','MICRONESIA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/fm.svg'),
	 (151,'MOLDAVIA','MD','Moldova, Republic of','MDA',498,373,'+','MOLDAVA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/md.svg'),
	 (152,'MONACO','MC','Monaco','MCO',492,377,'+','MONEGASCA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/mc.svg'),
	 (37,'CAMERUN','CM','Cameroon','CMR',120,237,'+','CAMERUNESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cm.svg'),
	 (38,'CANADA','CA','Canada','CAN',124,1,'+','CANADIENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ca.svg'),
	 (39,'CAPE VERDE','CV','Cape Verde','CPV',132,238,'+','CABOVERDIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cv.svg'),
	 (40,'CHAD','TD','Chad','TCD',148,235,'+','CHADIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/td.svg'),
	 (41,'CHILE','CL','Chile','CHL',152,56,'+','CHILENA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cl.svg'),
	 (42,'CHINA','CN','China','CHN',156,86,'+','CHINA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cn.svg'),
	 (43,'CHIPRE','CY','Cyprus','CYP',196,357,'+','CHIPRIOTA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cy.svg'),
	 (44,'CIUDAD DEL VATICANO','VA','Holy See (Vatican City State)','VAT',336,39,'+','VATICANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/va.svg'),
	 (45,'COLOMBIA','CO','Colombia','COL',170,57,'+','COLOMBIANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/co.svg'),
	 (46,'COMOROS','KM','Comoros','COM',174,269,'+','COMORENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/km.svg'),
	 (47,'CONGO','CG','Congo','COG',178,242,'+','CONGOLEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cg.svg'),
	 (48,'COREA DEL NORTE','KP','Korea, Democratic Peoples Republic of','PRK',408,850,'+','NORCOREANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kp.svg'),
	 (49,'COREA DEL SUR','KR','Korea, Republic of','KOR',410,82,'+','SURCOREANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/kr.svg'),
	 (50,'COSTA DE MARFIL','CI','Cote dIvoire','CIV',384,225,'+','MARFILEÑA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ci.svg'),
	 (51,'COSTA RICA','CR','Costa Rica','CRI',188,506,'+','COSTARRICENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cr.svg'),
	 (52,'CROACIA','HR','Croatia','HRV',191,385,'+','CROATA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/hr.svg'),
	 (53,'CUBA','CU','Cuba','CUB',192,53,'+','CUBANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/cu.svg'),
	 (54,'DINAMARCA','DK','Denmark','DNK',208,45,'+','DANESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/dk.svg'),
	 (209,'SOMALIA','SO','Somalia','SOM',706,252,'+','SOMALÍ','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/so.svg'),
	 (210,'SRI LANKA','LK','Sri Lanka','LKA',144,94,'+','SRI LANKENSE','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/lk.svg'),
	 (211,'SUAZILANDIA','SZ','Swaziland','SWZ',748,268,'+','SWAZI','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sz.svg'),
	 (212,'SUDAFRICA','ZA','South Africa','ZAF',710,27,'+','SUDAFRICANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/za.svg'),
	 (213,'SUDAN','SD','Sudan','SDN',729,249,'+','SUDANÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sd.svg'),
	 (214,'SUDAN DEL SUR','SS','South Sudan','SSD',728,211,'+','SUDSUDANÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ss.svg'),
	 (215,'SUECIA','SE','Sweden','SWE',752,46,'+','SUECA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/se.svg'),
	 (216,'SUIZA','CH','Switzerland','CHE',756,41,'+','SUIZA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/ch.svg'),
	 (217,'SURINAM','SR','Suriname','SUR',740,597,'+','SURINAMESA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/sr.svg'),
	 (219,'TAILANDIA','TH','Thailand','THA',764,66,'+','TAILANDÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/th.svg'),
	 (220,'TAIWAN','TW','Taiwan, Province of China','TWN',158,886,'+','TAIWANÉSA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tw.svg'),
	 (221,'TANZANIA','TZ','Tanzania, United Republic of','TZA',834,255,'+','TANZANA','https://s3.us-east-2.amazonaws.com/backoffice.documents/Countries/tz.svg');